name: analytics_event
description: Code generator to simplify generating analytics tracking events. Turns stub methods
    into tracking calls for fire base analytics, google analytics, etc.
version: 1.2.1
homepage: https://github.com/hpoul/analytics_events/

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  meta: ">=1.7.0 <2.0.0"

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.1.8
