name: dart_event_gen_example

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analytics_event:
    path: ../
  logging: ^1.0.1
  logging_appenders: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.11
  analytics_event_gen:
    path: ../../analytics_event_gen

dependency_overrides:
  analytics_event:
    path: ../
  analytics_event_gen:
    path: ../../analytics_event_gen

