name: analytics_event_gen
description: Auto generate tracking code for typesafe analytics.
version: 0.1.0
homepage: https://github.com/hpoul/analytics_events/

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.5
  pedantic: ^1.9.0
  code_builder: ^3.2.1
