name: analytics_event_gen
description: Code generator to simplify generating analytics tracking events. Turns stub methods
    into tracking calls for fire base analytics, google analytics, etc.
version: 0.1.2
homepage: https://github.com/hpoul/analytics_events/

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  analytics_event: 0.1.2
  build: ">=1.2.2 <2.0.0"
  source_gen: ^0.9.5
  code_builder: ^3.2.1
  built_collection: ^4.3.2
  dart_style: ">=1.3.4 <2.0.0"
  analyzer: ">=0.39.6 <1.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.8.1
