name: analytics_event_gen
description: Code generator to simplify generating analytics tracking events. Turns stub methods
    into tracking calls for fire base analytics, google analytics, etc.
version: 1.2.0
homepage: https://github.com/hpoul/analytics_events/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analytics_event: ^1.2.0
  build: ">=2.0.0 <3.0.0"
  source_gen: ">=1.0.0 <2.0.0"
  code_builder: ">=4.0.0 <5.0.0"
  built_collection: ">=5.0.0 <6.0.0"
  dart_style: ">=2.0.1 <3.0.0"
  analyzer: ">=1.5.0 <4.0.0"
  logging: ">=1.0.0 <2.0.0"
  recase: ">=4.0.0 <5.0.0"

dev_dependencies:
  build_runner: ">=2.0.2 <3.0.0"
  lints: ^1.0.1
